[[navbar]]
  identifier = "about"
  name = "A propos"
  url = "/fr/about/"
  weight = 1
[[navbar]]
  identifier = "hobbies"
  name = "Hobbies"
  url = "/fr/hobbies/"
  weight = 2
[[navbar]]
  identifier = "projects"
  name = "Projets"
  url = "/fr/projects/"
  weight = 3
[[navbar]]
  identifier = "posts"
  name = "Postes"
  url = "/fr/posts/"
  weight = 4
  [[navbar]]
    identifier = "blog"
    name = "Blog"
    url = "/fr/posts/blog"
    parent = "posts"
    weight = 1
  [[navbar]]
    identifier = "journal"
    name = "Journal"
    url = "/fr/posts/journal"
    parent = "posts"
    weight = 2